"""initial schema: all 10 tables

Revision ID: f0d86e4e7bcc
Revises: 
Create Date: 2026-06-11 17:13:38.763969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0d86e4e7bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('abandoned_sessions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed_orders', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('revenue_paise', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_session_s', sa.Integer(), nullable=True),
    sa.Column('avg_satisfaction', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('top_product_id', sa.String(length=50), nullable=True),
    sa.Column('top_design_theme', sa.String(length=50), nullable=True),
    sa.Column('total_agent_calls', sa.Integer(), nullable=True),
    sa.Column('total_tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('total_images_gen', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('inventory',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('print_area', sa.String(length=50), nullable=True),
    sa.Column('min_complexity', sa.String(length=10), server_default=sa.text("'simple'"), nullable=True),
    sa.Column('max_complexity', sa.String(length=10), server_default=sa.text("'complex'"), nullable=True),
    sa.Column('production_time_min', sa.SmallInteger(), nullable=True),
    sa.Column('margin_percent', sa.SmallInteger(), nullable=True),
    sa.Column('units_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('units_sold', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('units_reserved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reorder_level', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('design_fit_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sizes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_state', sa.String(length=32), server_default=sa.text("'idle'"), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('abandoned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('satisfaction_score', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('device_id', sa.String(length=50), nullable=True),
    sa.Column('prompt_variant', sa.String(length=20), server_default=sa.text("'v1'"), nullable=False),
    sa.CheckConstraint('satisfaction_score BETWEEN 1 AND 5', name='ck_sessions_satisfaction'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_completed', 'sessions', ['completed', 'created_at'], unique=False)
    op.create_index('idx_sessions_created', 'sessions', ['created_at'], unique=False)
    op.create_index('idx_sessions_state', 'sessions', ['current_state'], unique=False)
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_name', sa.String(length=30), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('prompt_version', sa.String(length=40), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_microdollars', sa.Integer(), nullable=True),
    sa.Column('execution_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_agent', 'agent_logs', ['agent_name', 'created_at'], unique=False)
    op.create_index('idx_agent_logs_session', 'agent_logs', ['session_id', 'created_at'], unique=False)
    op.create_table('conversation_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('turn_number', sa.SmallInteger(), nullable=False),
    sa.Column('input_type', sa.String(length=10), nullable=False),
    sa.Column('customer_input', sa.Text(), nullable=False),
    sa.Column('agent_response', sa.Text(), nullable=True),
    sa.Column('agent_text_reply', sa.Text(), nullable=True),
    sa.Column('story_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('clarification_needed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('clarity_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.CheckConstraint("input_type IN ('text')", name='ck_conv_input_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_session', 'conversation_logs', ['session_id', 'turn_number'], unique=False)
    op.create_table('designs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('story_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('story_version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('design_prompt_base', sa.Text(), nullable=False),
    sa.Column('design_strategy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('design_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_variant_id', sa.UUID(), nullable=True),
    sa.Column('refinements_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('regenerations_count', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('design_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendations_generated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('recommendations_model', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['selected_variant_id'], ['design_variants.id'], name='fk_designs_selected_variant', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_designs_session', 'designs', ['session_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('name_tag_text', sa.String(length=15), nullable=True),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('discount_paise', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('tax_paise', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=True),
    sa.Column('payment_status', sa.String(length=15), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('payment_ref', sa.String(length=100), nullable=True),
    sa.Column('order_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("order_status IN ('pending', 'queued', 'printing', 'pressing', 'stitching', 'complete', 'cancelled')", name='ck_orders_order_status'),
    sa.CheckConstraint("payment_method IN ('upi', 'card', 'cash')", name='ck_orders_payment_method'),
    sa.CheckConstraint("payment_status IN ('pending', 'completed', 'failed', 'refunded')", name='ck_orders_payment_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_session', 'orders', ['session_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['order_status', 'created_at'], unique=False)
    op.create_table('design_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('variant_number', sa.SmallInteger(), nullable=False),
    sa.Column('is_initial_set', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('prompt_used', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('style', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('fal_request_id', sa.String(length=100), nullable=True),
    sa.Column('generation_seed', sa.BigInteger(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_refined', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('parent_variant_id', sa.UUID(), nullable=True),
    sa.Column('refinement_type', sa.String(length=30), nullable=True),
    sa.Column('refinement_value', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_variant_id'], ['design_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variants_design', 'design_variants', ['design_id'], unique=False)
    op.create_index('idx_variants_initial', 'design_variants', ['design_id', 'is_initial_set'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('design_variant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=5), nullable=True),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('unit_price_paise', sa.Integer(), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['design_variant_id'], ['design_variants.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_items_order', 'order_items', ['order_id'], unique=False)
    op.create_index('idx_order_items_variant', 'order_items', ['design_variant_id'], unique=False)
    op.create_table('production_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('design_file_path', sa.Text(), nullable=True),
    sa.Column('print_status', sa.String(length=15), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('print_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('print_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('print_duration_s', sa.Integer(), nullable=True),
    sa.Column('press_status', sa.String(length=15), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('press_started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('press_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('stitch_status', sa.String(length=15), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('stitch_completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('quality_check_passed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("press_status IN ('queued','pressing','complete','failed')", name='ck_jobs_press_status'),
    sa.CheckConstraint("print_status IN ('queued','printing','complete','failed')", name='ck_jobs_print_status'),
    sa.CheckConstraint("stitch_status IN ('queued','stitching','complete','skipped')", name='ck_jobs_stitch_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_order', 'production_jobs', ['order_id'], unique=False)
    op.create_index('idx_jobs_status', 'production_jobs', ['print_status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_status', table_name='production_jobs')
    op.drop_index('idx_jobs_order', table_name='production_jobs')
    op.drop_table('production_jobs')
    op.drop_index('idx_order_items_variant', table_name='order_items')
    op.drop_index('idx_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('idx_variants_initial', table_name='design_variants')
    op.drop_index('idx_variants_design', table_name='design_variants')
    op.drop_table('design_variants')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_session', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_designs_session', table_name='designs')
    op.drop_table('designs')
    op.drop_index('idx_conv_session', table_name='conversation_logs')
    op.drop_table('conversation_logs')
    op.drop_index('idx_agent_logs_session', table_name='agent_logs')
    op.drop_index('idx_agent_logs_agent', table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_index('idx_sessions_state', table_name='sessions')
    op.drop_index('idx_sessions_created', table_name='sessions')
    op.drop_index('idx_sessions_completed', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('inventory')
    op.drop_table('analytics')
    # ### end Alembic commands ###
