# Required status check for merging PRs to main.
name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    uses: ./.github/workflows/backend.yml

  frontend:
    uses: ./.github/workflows/frontend.yml
